spring.application.name=EcommProjectversion1
spring.datasource.url=jdbc:mysql://localhost:3306/my_project
spring.datasource.username=root
spring.datasource.password=Vishnu@11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
cloudinary.cloud-name=kus7lxsh
cloudinary.api-key=719112617529917
cloudinary.api-secret=1LrGK0BRNGZNM3VLUK2yVsFfjZg

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vishnumedhas11@gmail.com
spring.mail.password=qpwraayaerjzpaow

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true